<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ImageForms\iconForApp.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ImageForms\box.png" />
    <None Remove="ImageForms\iconForApp.ico" />
    <None Remove="ImageForms\iconForQuiz.ico" />
    <None Remove="ImageForms\iconForSearch.ico" />
    <None Remove="ImageForms\system.png" />
    <None Remove="Properties\quiz_advanced.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ImageForms\box.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageForms\iconForApp.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageForms\iconForQuiz.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageForms\iconForSearch.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageForms\system.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\quiz_advanced.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net8.0-windows\" />
  </ItemGroup>

</Project>